# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - recall-server

on:
  push:
    branches:
      - diff-version
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_104c2e2fd08441f48d1c9236001da964 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5482cdfe7ed9481cbacb110a9e7523a8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_104c2e2fd08441f48d1c9236001da964 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'recall-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_27d5ab01e6ef40e780206b5532823ffb }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_104c2e2fd08441f48d1c9236001da964 }}/appsvc/staticsite:${{ github.sha }}'